version: '3.8' 
services: 
  backend: 
    build: ./backend 
    ports: 
      - "8000:8000" 
    environment: 
      - DATABASE_URL=postgresql://physiotech_root:24680Ua***@host.docker.internal:5432/physiotech_control 
